language: cpp

sudo: required
dist: trusty

addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    # install toolchains
    - gcc-5
    - g++-5

script:
  - cmake .
  - cmake --build .

deploy:
  provider: releases
  api_key: "4cb33ab92b85058ad126ebb1b237f24d080b3e73"
  file: "nalparser"
  skip_cleanup: true
  on:
    tags: true
